/**
 * Loader for per-repo weekly time-series data.
 * Fetches from /public/data/timeseries/[repoId].json (generated by aggregate-timeseries.mjs).
 * Each file contains ContributorPerformanceDataPoint[] for the top 15 contributors.
 */

import type { ContributorPerformanceDataPoint } from "@/lib/dashboard/entities/contributor/types";

export type RepoTimeseriesFile = {
  schemaVersion: string;
  generatedAt: string;
  repoId: string;
  granularity: "weekly";
  topContributors: string[];
  /** Lifetime additions+deletions per top contributor (schemaVersion 1.1+) */
  lifetimeTotals?: Record<string, { additions: number; deletions: number }>;
  data: ContributorPerformanceDataPoint[];
};

const cache = new Map<string, RepoTimeseriesFile>();

/**
 * Fetch weekly timeseries for a repo.
 * Returns null if the file doesn't exist (scripts not run yet).
 */
export async function getRepoTimeseriesData(
  repoId: string
): Promise<RepoTimeseriesFile | null> {
  if (cache.has(repoId)) return cache.get(repoId)!;

  try {
    const res = await fetch(`/data/timeseries/${repoId}.json`);
    if (!res.ok) return null;
    const data = (await res.json()) as RepoTimeseriesFile;
    cache.set(repoId, data);
    return data;
  } catch {
    return null;
  }
}

/** Clear the in-memory cache (for testing) */
export function clearRepoTimeseriesCache(): void {
  cache.clear();
}
