import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LightThemeScript } from "@/components/shared/LightThemeScript";
import { TimeRangeProvider } from "@/lib/dashboard/shared/contexts/TimeRangeContext";
import { ConditionalLayout } from "@/components/shared/ConditionalLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LightThemeScript />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <TimeRangeProvider config={{ defaultRange: "1y" }}>
          <ConditionalLayout>{children}</ConditionalLayout>
        </TimeRangeProvider>
      </body>
    </html>
  );
}
